"""Evidence sheet for corporate actions awaiting confirmation.

    python scripts/review_evidence.py    -> docs/CA_REVIEW_EVIDENCE.md

For every pending `needs_review` row it downloads the source PDF from cdn.cse.lk (cached in
.cache/ca_pdfs/, not committed), extracts the text with `pdftotext`, quotes the sentences that
state the ratio, price and dates, and checks whether the parsed numbers appear in the PDF.

It suggests; it never confirms. Confirmation stays a human decision in
config/corporate_actions_review.yaml (the brief: "list them on the site for me to confirm").
"""
from __future__ import annotations

import re
import subprocess
import sys
import time
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from cse import corpactions, storage  # noqa: E402
from cse.fetch import Paths  # noqa: E402
from cse.http import USER_AGENT  # noqa: E402

CACHE = ROOT / ".cache" / "ca_pdfs"
KEYS = re.compile(r"for every|for each|existing|ratio|proportion|consideration|subscription|issue price|"
                  r"price of rs|rs\.?\s*\d|xr|ex[- ]?rights|ex[- ]?dividend|xd|record date|commencement|"
                  r"date of|dividend of|per share|scrip|allot", re.I)


def pdf_text(url: str, rid: str, session: requests.Session) -> str | None:
    CACHE.mkdir(parents=True, exist_ok=True)
    pdf = CACHE / (re.sub(r"[^\w.+-]", "_", rid) + ".pdf")
    if not pdf.exists():
        for attempt in range(3):
            try:
                r = session.get(url, timeout=30)
                time.sleep(1)
                if r.status_code == 200 and r.content[:4] == b"%PDF":
                    pdf.write_bytes(r.content)
                    break
            except requests.RequestException:
                time.sleep(2 ** (attempt + 1))
        else:
            return None
    out = subprocess.run(["pdftotext", "-layout", str(pdf), "-"], capture_output=True, text=True)
    return out.stdout if out.returncode == 0 else None


def snippets(text: str, limit: int = 8) -> list[str]:
    lines = [re.sub(r"\s+", " ", ln).strip() for ln in text.splitlines()]
    hits = [ln for ln in lines if ln and KEYS.search(ln) and len(ln) > 12]
    seen, out = set(), []
    for h in hits:
        if h.lower() not in seen:
            seen.add(h.lower())
            out.append(h[:220])
        if len(out) >= limit:
            break
    return out


def _num_in(text: str, value: str) -> bool:
    if not value:
        return False
    v = float(value)
    forms = {f"{v:g}", f"{v:.2f}", f"{int(v):02d}" if v.is_integer() else f"{v:g}"}
    return any(re.search(rf"(?<![\d.]){re.escape(f)}(?![\d])", text) for f in forms)


def _same(a, b) -> bool:
    try:
        return abs(float(a) - float(b)) < 1e-6
    except (TypeError, ValueError):
        return str(a) == str(b)


def _flow(d: dict) -> str:
    if not d:
        return "{}"
    return "{" + ", ".join(f"{k}: {v}" for k, v in d.items()) + "}"


def main() -> None:
    paths = Paths(ROOT)
    rows = storage.read_rows(paths.history / "corporate_actions.csv")
    reviews = corpactions.load_reviews(ROOT / "config" / "corporate_actions_review.yaml")
    pending = corpactions.pending_review(rows, reviews)
    s = requests.Session()
    s.headers["User-Agent"] = USER_AGENT
    out = ["# Corporate actions awaiting confirmation: evidence sheet\n",
           "Generated by `python scripts/review_evidence.py` from the source PDFs on cdn.cse.lk. "
           "**These are suggestions; nothing here is confirmed.** You confirm or reject each row in "
           "`config/corporate_actions_review.yaml` after reading its PDF (link in each heading).\n",
           "\"PDF agrees\" means each parsed number (ratio, subscription price) appears verbatim in the PDF "
           "text. It doesn't prove the reading is right, so read the quoted lines.\n"]
    import yaml
    readings = yaml.safe_load((ROOT / "docs" / "ca_review_readings.yaml").read_text()) or {}
    suggestion, rejects = [], []
    for r in pending:
        text = pdf_text(r["source_url"], r["id"], s) if r["source_url"] else None
        checks = []
        for label, key in (("new", "ratio_new"), ("held", "ratio_held"), ("price", "subscription_price"),
                           ("amount", "amount_per_share")):
            if r.get(key):
                checks.append((label, r[key], bool(text and _num_in(text, r[key]))))
        agrees = bool(checks) and all(c[2] for c in checks)
        out.append(f"## `{r['id']}`: {r['symbol']} {r['type']}, ex {r['ex_date'] or 'not stated'}\n")
        out.append(f"[Source PDF]({r['source_url']}) · parser note: {r['note']}\n" if r["source_url"] else
                   f"No source PDF · parser note: {r['note']}\n")
        if checks:
            out.append("| Parsed field | Value | Found in PDF |\n|---|---|---|")
            out += [f"| {lab} | {val} | {'yes' if ok else '**no**'} |" for lab, val, ok in checks]
            out.append("")
        if text:
            out.append("Relevant lines from the PDF:\n")
            out += [f"> {ln}  " for ln in snippets(text)] or ["> (no matching lines; read the PDF)"]
            out.append("")
        else:
            out.append("_PDF could not be read; check it manually._\n")
        missing = [k for k in ("ex_date", "ratio_new", "ratio_held") if not r.get(k)]
        if r["type"] == "rights" and not r.get("subscription_price"):
            missing.append("subscription_price")
        if r["type"] == "cash_dividend":
            missing = [k for k in ("ex_date", "amount_per_share") if not r.get(k)]
        verdict = ("PDF agrees with the parsed values" if agrees and not missing else
                   f"Needs your input: {', '.join(missing)}" if missing else "Check manually: numbers not all found")
        rd = readings.get(r["id"])
        if rd:
            fields = {k: rd[k] for k in ("ex_date", "ratio_new", "ratio_held", "subscription_price", "amount_per_share") if k in rd}
            diffs = {k: v for k, v in fields.items() if str(v) != str(r.get(k) or "") and
                     not (r.get(k) and _same(r[k], v))}
            out.append(f"**Claude's reading of the PDF** ({rd.get('pdf', '')}): "
                       + ", ".join(f"{k} = {v}" for k, v in fields.items())
                       + (f". *{rd['note']}*" if rd.get("note") else "") + "\n")
            verdict = {"confirm": "matches the parsed values: confirm",
                       "confirm_with": f"confirm, supplying {diffs}",
                       "reject": "reject", "needs_input": "needs your input"}[rd["suggest"]]
            if rd["suggest"] == "confirm" and diffs:
                verdict = f"confirm, correcting {diffs}"
            if rd["suggest"] in ("confirm", "confirm_with"):
                suggestion.append(f'  "{r["id"]}": {_flow(diffs)}   # {r["symbol"]} {r["type"]} ex {fields.get("ex_date", r["ex_date"])}')
            elif rd["suggest"] == "reject":
                rejects.append(f'  - "{r["id"]}"   # {r["symbol"]}: {rd.get("note", "")[:70]}')
        out.append(f"**Suggested:** {verdict}.\n")
    out.append("## Suggested `config/corporate_actions_review.yaml`\n")
    out.append("Built from Claude's readings above. **Check each against its PDF before adopting it.** "
               "Rows needing your input (missing ex-date or price not in any PDF) are left out.\n")
    out.append("```yaml\nconfirm:\n" + ("\n".join(suggestion) if suggestion else "  {}")
               + "\nreject:\n" + ("\n".join(rejects) if rejects else "  []") + "\n```\n")
    (ROOT / "docs" / "CA_REVIEW_EVIDENCE.md").write_text("\n".join(out))
    print(f"wrote docs/CA_REVIEW_EVIDENCE.md: {len(pending)} rows, {len(suggestion)} suggested confirmations, "
          f"{len(rejects)} suggested rejections")


if __name__ == "__main__":
    main()
